### Notification Get

GET {{host}}/Notification


### Notification Create Discord

POST {{host}}/Notification
Content-Type: application/json

{
	"Data":
    {
        "Type": "Discord",
        "Name": "ITCM 핫딜",
        "IconUrl": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/6b/6b9915f60cb45d4df113cd8f36387ba1de8ce601_full.jpg",
        "HookUrl": "https://discordapp.com/api/webhooks/757093885078929458/Ao4NQdGJxyF--6KZhzOX5WVIn9oungNGepQUXp3SQd0f3N5MbrhLG5bSb2QZUg0ypjLW",
        "CrawlingType": "Itcm",
        "BoardName": "핫딜"
    }
}

### Notification Create Multi Discord

POST {{host}}/Notification/Multi
Content-Type: application/json

{
	"Datas": [
        {
			"Type": "Discord",
			"Name": "핫딜",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://discordapp.com/api/webhooks/757093885078929458/Ao4NQdGJxyF--6KZhzOX5WVIn9oungNGepQUXp3SQd0f3N5MbrhLG5bSb2QZUg0ypjLW",
            "CrawlingType": "Ruliweb",
            "BoardName": "핫딜게시판"
		},
        {
			"Type": "Discord",
			"Name": "콘솔뉴스",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://discordapp.com/api/webhooks/757093886328832130/jKs9EL3-Q7XzP1f6tJUXDGu-SOEAQHWzrR42MfJwz0NB2jpAWsBVoTb8sm7Tt7YTub47",
            "CrawlingType": "Ruliweb",
            "BoardName": "콘솔뉴스"
		},
        {
			"Type": "Discord",
			"Name": "PC뉴스",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://discordapp.com/api/webhooks/749487855423717480/Nv35ssFNegqBdzpMiG5lTQYM9P4B8uff_hGcbwAvECt51zyq9vwOGyDAI86LiDzneoQb",
            "CrawlingType": "Ruliweb",
            "BoardName": "PC뉴스"
		},
        {
			"Type": "Discord",
			"Name": "많이 본 글",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://discordapp.com/api/webhooks/757093883900461057/08cT2nsXg1GoaY7zBxtpC53ODb_PaQpy_tRbIAkKlajJlcpnZPuLfhhvX04mABlutlv7",
            "CrawlingType": "Ruliweb",
            "BoardName": "많이 본 글",
            "FilterDayOfWeeks": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 
            "FilterStartTime": "09:00:00",
            "FilterEndTime": "19:00:00",
		},
        {
			"Type": "Discord",
			"Name": "베오베",
            "IconUrl": "https://apprecs.org/ios/images/app-icons/256/6f/664550767.jpg",
            "HookUrl": "https://discordapp.com/api/webhooks/757093883900461057/08cT2nsXg1GoaY7zBxtpC53ODb_PaQpy_tRbIAkKlajJlcpnZPuLfhhvX04mABlutlv7",
            "CrawlingType": "TodayHumor",
            "BoardName": "베오베",
            "FilterDayOfWeeks": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 
            "FilterStartTime": "09:00:00",
            "FilterEndTime": "19:00:00",
		},
        {
			"Type": "Discord",
			"Name": "축구 뉴스",
            "IconUrl": "https://media.cdnandroid.com/item_images/1047984/imagen-i-i-i-ee-i-i-i-0thumb.jpeg",
            "HookUrl": "https://discordapp.com/api/webhooks/757111653832589412/JgGoutmu-ZrN6VVMUrm8kOGR0pk1WKd74TVig5UNBlrkwEMUYqC2-d4T3wY3Q-yltp8w",
            "CrawlingType": "FmKorea",
            "BoardName": "축구 뉴스",
            "Keyword": "토트넘"
		},
        {
			"Type": "Discord",
			"Name": "Rss",
            "IconUrl": "https://www.bruegel.org/wp-content/uploads/2015/08/icon-rss.png",
            "HookUrl": "https://discordapp.com/api/webhooks/757093883438956604/YRdxA4KgvT0cEdzECC8bu4DyeSIuoxlLhMfPoG3BQgtrn1-fpArcr1ogo7uMTqK-QeKG",
            "CrawlingType": "Rss"
		},
        {
            "Type": "Discord",
            "Name": "LOL 리포터 뉴스",
            "IconUrl": "https://lh3.googleusercontent.com/Hc4D74YO7FYttrPCm5MuDm91NLblaaunJ6Y38WCg9mABUJfobgU_vXy1tjX668bI6xs=s180-rw",
            "HookUrl": "https://discordapp.com/api/webhooks/763802481817026580/eSwxNI_pfy0V2zMtAEwLDydZ2zM7GilP-KPsZR5rGcYTCdlkPz9mFaUbl4BI7oI7RmtF",
            "CrawlingType": "InvenNews",
            "BoardName": "인벤 LOL 뉴스"
        },
        {
            "Type": "Discord",
            "Name": "펨코핫딜",
            "IconUrl": "https://media.cdnandroid.com/item_images/1047984/imagen-i-i-i-ee-i-i-i-0thumb.jpeg",
            "HookUrl": "https://discordapp.com/api/webhooks/757093885078929458/Ao4NQdGJxyF--6KZhzOX5WVIn9oungNGepQUXp3SQd0f3N5MbrhLG5bSb2QZUg0ypjLW",
            "CrawlingType": "FmKorea",
            "BoardName": "핫딜"
        },
        {
            "Type": "Discord",
            "Name": "포텐터짐",
            "IconUrl": "https://media.cdnandroid.com/item_images/1047984/imagen-i-i-i-ee-i-i-i-0thumb.jpeg",
            "HookUrl": "https://discordapp.com/api/webhooks/757093883900461057/08cT2nsXg1GoaY7zBxtpC53ODb_PaQpy_tRbIAkKlajJlcpnZPuLfhhvX04mABlutlv7",
            "CrawlingType": "FmKorea",
            "BoardName": "포텐터짐",
            "Keyword": "LOL|LCK|DRX|손흥민",
            "FilterDayOfWeeks": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 
            "FilterStartTime": "09:00:00",
            "FilterEndTime": "19:00:00",
        },
        {
            "Type": "Discord",
            "Name": "인기자료",
            "IconUrl": "http://down.humoruniv.com/hwiparambbs/data/pdswait/a_4883065431_b9afd56add3ad86ccc10cde95a0d8c0cc57ead30.png",
            "HookUrl": "https://discordapp.com/api/webhooks/757093883900461057/08cT2nsXg1GoaY7zBxtpC53ODb_PaQpy_tRbIAkKlajJlcpnZPuLfhhvX04mABlutlv7",
            "CrawlingType": "HumorUniv",
            "BoardName": "인기자료",
            "FilterDayOfWeeks": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 
            "FilterStartTime": "09:00:00",
            "FilterEndTime": "19:00:00",
        },
        {
            "Type": "Discord",
            "Name": "알뜰구매",
            "IconUrl": "https://cdn.clien.net/web/api/file/F01/2581830/94f801b57da24373a43.PNG",
            "HookUrl": "https://discordapp.com/api/webhooks/757093885078929458/Ao4NQdGJxyF--6KZhzOX5WVIn9oungNGepQUXp3SQd0f3N5MbrhLG5bSb2QZUg0ypjLW",
            "CrawlingType": "Clien",
            "BoardName": "알뜰구매"
        },
        {
            "Type": "Discord",
            "Name": "핫딜",
            "IconUrl": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/6b/6b9915f60cb45d4df113cd8f36387ba1de8ce601_full.jpg",
            "HookUrl": "https://discordapp.com/api/webhooks/757093885078929458/Ao4NQdGJxyF--6KZhzOX5WVIn9oungNGepQUXp3SQd0f3N5MbrhLG5bSb2QZUg0ypjLW",
            "CrawlingType": "Itcm",
            "BoardName": "핫딜"
        }
	]
}

### Notification Create Multi Discord (클리앙 중고장터)

POST {{host}}/Notification/Multi
Content-Type: application/json

{
	"Datas": [
        {
			"Type": "Discord",
			"Name": "중고장터",
            "IconUrl": "https://cdn.clien.net/web/api/file/F01/2581830/94f801b57da24373a43.PNG",
            "HookUrl": "https://discordapp.com/api/webhooks/757093885569663077/RaNvzjzoIrFTZDhutMEFq9pRQlqpkSqLChH8CcB2SDsMjY-gbghowJn0DGn-Lg09vSNj",
            "CrawlingType": "Clien",
            "BoardName": "회원중고장터",
            "Keyword": "PC|게임|태블릿"
		}
	]
}


### Notification Create Multi Discord (for local debug)

POST {{host}}/Notification/Multi
Content-Type: application/json

{
	"Datas": [
        {
			"Type": "Discord",
			"Name": "핫딜",
            "IconUrl": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/6b/6b9915f60cb45d4df113cd8f36387ba1de8ce601_full.jpg",
            "HookUrl": "https://discordapp.com/api/webhooks/757093882747158622/m2mrsgUWaPIzi8K7DjuRTLmUZet5VuNllhKRkekhcx_MSNHSRTdmuSISq67HlwN1ehJ6",
            "CrawlingType": "Itcm",
            "BoardName": "핫딜"
		}
	]
}



### Notification Create Multi Slack

POST {{host}}/Notification/Multi
Content-Type: application/json

{
	"Datas": [
        {
			"Type": "Slack",
			"Name": "장터",
            "Channel": "C01AW5D68Q3",
            "IconUrl": "https://cdn.clien.net/web/api/file/F01/2581830/94f801b57da24373a43.PNG",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Clien",
            "BoardName": "회원중고장터"
		},
        {
			"Type": "Slack",
			"Name": "핫딜",
            "Channel": "CMEGGHK3J",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "핫딜게시판"
		},
        {
			"Type": "Slack",
			"Name": "콘솔뉴스",
            "Channel": "CMGCFNG6B",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "콘솔뉴스"
		},
        {
			"Type": "Slack",
			"Name": "PC뉴스",
            "Channel": "C017G0KHBKM",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "PC뉴스"
		},
        {
			"Type": "Slack",
			"Name": "많이 본 글",
            "Channel": "C01AW22MX5Y",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "많이 본 글"
		},
        {
			"Type": "Slack",
			"Name": "축구 뉴스",
            "Channel": "CMEGGM5NC",
            "IconUrl": "https://media.cdnandroid.com/item_images/1047984/imagen-i-i-i-ee-i-i-i-0thumb.jpeg",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "FmKorea",
            "BoardName": "축구 뉴스"
		},
        {
			"Type": "Slack",
			"Name": "베오베",
            "Channel": "C01AW22MX5Y",
            "IconUrl": "https://apprecs.org/ios/images/app-icons/256/6f/664550767.jpg",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "TodayHumor",
            "BoardName": "베오베"
		}
	]
}

### Notification Create Multi Slack (for local debug)

POST {{host}}/Notification/Multi
Content-Type: application/json

{
	"Datas": [
        {
			"Type": "Slack",
			"Name": "장터",
            "Channel": "C01AVLPP1U5",
            "IconUrl": "https://cdn.clien.net/web/api/file/F01/2581830/94f801b57da24373a43.PNG",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Clien",
            "BoardName": "회원중고장터"
		},
        {
			"Type": "Slack",
			"Name": "핫딜",
            "Channel": "C01AVLPP1U5",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "핫딜게시판"
		},
        {
			"Type": "Slack",
			"Name": "콘솔뉴스",
            "Channel": "C01AVLPP1U5",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "콘솔뉴스"
		},
        {
			"Type": "Slack",
			"Name": "PC뉴스",
            "Channel": "C01AVLPP1U5",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "PC뉴스"
		},
        {
			"Type": "Slack",
			"Name": "많이 본 글",
            "Channel": "C01AW22MX5Y",
            "IconUrl": "https://lh3.googleusercontent.com/OwN24ti7VzhNXGWVw4RQD-dfkGEf-fnFb7yz--knAwPoxR9VSXpGb3UoOYJNyDIKiQ=s180",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "Ruliweb",
            "BoardName": "많이 본 글"
		},
        {
			"Type": "Slack",
			"Name": "축구 뉴스",
            "Channel": "C01AVLPP1U5",
            "IconUrl": "https://media.cdnandroid.com/item_images/1047984/imagen-i-i-i-ee-i-i-i-0thumb.jpeg",
            "HookUrl": "https://hooks.slack.com/services/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",
            "CrawlingType": "FmKorea",
            "BoardName": "축구 뉴스"
		}
	]
}

### Notification Get

GET {{host}}/Notification/5f5a25cc6e6fbaf1a5e7ccca

### Notification Update

PUT {{host}}/Notification/5f5a25cc6e6fbaf1a5e7ccca
Content-Type: application/json

{
    "Data": {
        "Id": "5f5a25cc6e6fbaf1a5e7ccca",
        "Type": "Slack",
        "Name": "축구 뉴스",
        "Channel": "C01AVLPP1U5",
        "IconUrl": "https://media.cdnandroid.com/item_images/1047984/imagen-i-i-i-ee-i-i-i-0thumb.jpeg",
        "HookUrl": "https://hooks.slack.com/services/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",
        "CrawlingType": "FmKorea",
        "BoardName": "축구 뉴스"
    }
}

### Notification Delete

DELETE {{host}}/Notification/5f5a25cc6e6fbaf1a5e7ccca

